"""
NCA pre-pre-training: train the slowrun architecture on NCA data.

Loads the portable slowrun model (slowrun_model.py) with NCA vocab (10002)
and trains on NCA data generated by nca_datagen.py.

Uses Adam optimizer (Muon requires multi-GPU), bf16 autocast.
Supports DDP multi-GPU training via torchrun.

Usage (single GPU):
    python pretrain.py --data-dir ./data --config tiny

Usage (multi-GPU):
    torchrun --standalone --nproc_per_node=4 pretrain.py --data-dir ./data --config full
"""

import argparse
import contextlib
import math
import os
import time

import torch
import torch.nn.functional as F
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import Dataset, DataLoader, DistributedSampler

from model import GPT, GPTConfig

# ── Configs ──────────────────────────────────────────────────────────────────

CONFIGS = {
    "tiny": dict(
        n_layer=4, n_head=4, n_kv_head=4, n_embd=256,
        batch_size=64, grad_accum=1, lr=1e-3, epochs=3,
    ),
    "small": dict(
        n_layer=12, n_head=8, n_kv_head=8, n_embd=768,
        batch_size=32, grad_accum=2, lr=3e-4, epochs=3,
    ),
    "tiny-track": dict(
        n_layer=16, n_head=8, n_kv_head=8, n_embd=1024,
        batch_size=16, grad_accum=2, lr=2e-4, epochs=3,
    ),
    "full": dict(
        n_layer=30, n_head=14, n_kv_head=14, n_embd=1792,
        batch_size=8, grad_accum=8, lr=1e-4, epochs=3,
    ),
}


# ── Dataset ──────────────────────────────────────────────────────────────────

class SequenceDataset(Dataset):
    """Wraps a (N, seq_len+1) token tensor as a Dataset for DataLoader."""
    def __init__(self, tokens, seq_len):
        self.tokens = tokens
        self.seq_len = seq_len

    def __len__(self):
        return self.tokens.shape[0]

    def __getitem__(self, idx):
        seq = self.tokens[idx]
        return seq[:self.seq_len], seq[1:self.seq_len + 1]


# ── Data loading ─────────────────────────────────────────────────────────────

def load_nca_data(data_dir, split="train"):
    path = os.path.join(data_dir, f"nca_{split}.pt")
    data = torch.load(path, weights_only=True)
    tokens = data["tokens"].long()
    return tokens


# ── Learning rate schedule ───────────────────────────────────────────────────

def get_lr(step, total_steps, max_lr, warmup_frac=0.05, min_lr_frac=0.1):
    """Cosine schedule with linear warmup."""
    warmup_steps = int(total_steps * warmup_frac)
    if step < warmup_steps:
        return max_lr * step / max(1, warmup_steps)
    progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
    return max_lr * (min_lr_frac + (1 - min_lr_frac) * 0.5 *
                     (1 + math.cos(math.pi * progress)))


# ── DDP helpers ──────────────────────────────────────────────────────────────

def setup_distributed():
    """Initialize DDP if launched via torchrun. Returns (rank, local_rank, world_size)."""
    if "RANK" not in os.environ:
        return 0, 0, 1  # single-GPU fallback
    dist.init_process_group(backend="nccl" if torch.cuda.is_available() else "gloo")
    rank = int(os.environ["RANK"])
    local_rank = int(os.environ["LOCAL_RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    if torch.cuda.is_available():
        torch.cuda.set_device(local_rank)
    return rank, local_rank, world_size


def cleanup_distributed():
    if dist.is_initialized():
        dist.destroy_process_group()


def get_batch(tokens, batch_size, seq_len, device, rng):
    """Sample a random batch of sequences (used for validation)."""
    n_seqs = tokens.shape[0]
    idx = torch.randint(0, n_seqs, (batch_size,), generator=rng)
    seqs = tokens[idx]
    x = seqs[:, :seq_len].to(device)
    y = seqs[:, 1:seq_len + 1].to(device)
    return x, y


# ── Training loop ────────────────────────────────────────────────────────────

def train(args):
    rank, local_rank, world_size = setup_distributed()
    is_main = rank == 0
    ddp = world_size > 1

    cfg = CONFIGS[args.config]
    seq_len = args.seq_len

    # Device selection
    if args.device is not None:
        device = args.device
    elif torch.cuda.is_available():
        device = f"cuda:{local_rank}"
    else:
        device = "cpu"

    if is_main:
        print(f"Config: {args.config}")
        print(f"Device: {device} (world_size={world_size})")

    # Load data
    train_tokens = load_nca_data(args.data_dir, "train")
    val_tokens = load_nca_data(args.data_dir, "val")

    if is_main:
        print(f"Loaded train: {train_tokens.shape}, val: {val_tokens.shape}")

    # Determine vocab size from data
    max_token = max(train_tokens.max().item(), val_tokens.max().item())
    vocab_size = max_token + 1
    if is_main:
        print(f"Vocab size: {vocab_size}")

    # Create model
    model_config = GPTConfig(
        vocab_size=vocab_size,
        n_layer=cfg["n_layer"],
        n_head=cfg["n_head"],
        n_kv_head=cfg["n_kv_head"],
        n_embd=cfg["n_embd"],
        sequence_len=seq_len,
        dropout=0.0,
    )
    model = GPT(model_config)
    model.init_weights()
    model = model.to(device)

    n_params = sum(p.numel() for p in model.parameters())
    if is_main:
        print(f"Model params: {n_params:,}")

    # torch.compile for fused kernels — big speedup on H100
    if device != "cpu" and not args.no_compile:
        if is_main:
            print("Compiling model with torch.compile...")
        model = torch.compile(model)

    # Wrap with DDP, use bf16 gradient reduction to halve comm volume
    if ddp:
        model = DDP(model, device_ids=[local_rank], gradient_as_bucket_view=True)

        def bf16_compress_hook(state, bucket: dist.GradBucket) -> torch.futures.Future[torch.Tensor]:
            compressed = bucket.buffer().to(torch.bfloat16)
            fut = dist.all_reduce(compressed, async_op=True).get_future()
            def decompress(fut_result):
                return fut_result.value()[0].to(torch.float32) / dist.get_world_size()
            return fut.then(decompress)

        model.register_comm_hook(state=None, hook=bf16_compress_hook)
    raw_model = model.module if ddp else model

    # Optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=cfg["lr"],
                                  betas=(0.9, 0.95), weight_decay=0.1)

    # Training setup — divide batch by world_size to keep effective batch constant
    batch_size = cfg["batch_size"] // world_size
    if batch_size < 1:
        batch_size = 1
    grad_accum = cfg["grad_accum"]
    effective_batch = batch_size * grad_accum * world_size
    tokens_per_step = effective_batch * seq_len

    # DataLoader with DistributedSampler for training
    train_dataset = SequenceDataset(train_tokens, seq_len)
    train_sampler = DistributedSampler(
        train_dataset, num_replicas=world_size, rank=rank, shuffle=True
    ) if ddp else None
    dl_workers = 2 if ddp else 0
    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, sampler=train_sampler,
        shuffle=(train_sampler is None), num_workers=dl_workers,
        pin_memory=(dl_workers > 0), drop_last=True,
    )

    n_train_tokens = train_tokens.shape[0] * seq_len
    steps_per_epoch = n_train_tokens // tokens_per_step
    total_steps = steps_per_epoch * cfg["epochs"]
    eval_interval = max(1, steps_per_epoch // 5)

    if is_main:
        print(f"Batch: {batch_size}/gpu x {grad_accum} accum x {world_size} gpus"
              f" = {effective_batch} effective")
        print(f"Steps/epoch: {steps_per_epoch}, total: {total_steps}")
        print(f"Eval every {eval_interval} steps")

    # bf16 autocast
    device_type = device.split(":")[0]
    use_amp = device_type != "cpu"
    amp_dtype = torch.bfloat16 if use_amp else torch.float32

    val_rng = torch.Generator()
    val_rng.manual_seed(123)

    best_val_loss = float("inf")
    t0 = time.time()
    step_t0 = t0
    step = 0

    for epoch in range(cfg["epochs"]):
        if train_sampler is not None:
            train_sampler.set_epoch(epoch)

        train_iter = iter(train_loader)

        while step < (epoch + 1) * steps_per_epoch and step < total_steps:
            # LR schedule
            lr = get_lr(step, total_steps, cfg["lr"])
            for pg in optimizer.param_groups:
                pg["lr"] = lr

            # Training step with gradient accumulation
            model.train()
            optimizer.zero_grad()
            train_loss_accum = 0.0

            for micro in range(grad_accum):
                try:
                    x, y = next(train_iter)
                except StopIteration:
                    train_iter = iter(train_loader)
                    x, y = next(train_iter)
                x, y = x.to(device), y.to(device)

                # Use no_sync for all but last micro-batch to avoid
                # redundant all-reduce during gradient accumulation
                ctx = model.no_sync() if (ddp and micro < grad_accum - 1) else \
                    contextlib.nullcontext()
                with ctx:
                    with torch.autocast(device_type=device_type,
                                        dtype=amp_dtype, enabled=use_amp):
                        loss = model(x, y) / grad_accum
                    loss.backward()
                train_loss_accum += loss.item()

            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            # Logging (rank 0 only)
            if is_main and step % 10 == 0:
                now = time.time()
                # Rolling tok/s over last 10 steps (instantaneous)
                dt = now - step_t0
                inst_tok_per_sec = 10 * tokens_per_step / dt if dt > 0 else 0
                step_t0 = now
                print(f"step {step:>5d}/{total_steps} | "
                      f"loss {train_loss_accum:.4f} | "
                      f"lr {lr:.2e} | {inst_tok_per_sec:,.0f} tok/s")

            # Evaluation (rank 0 only)
            if is_main and (step % eval_interval == 0 or step == total_steps - 1):
                model.eval()
                val_losses = []
                val_bs = min(cfg["batch_size"], val_tokens.shape[0])
                n_val_batches = max(1, min(20, val_tokens.shape[0] // val_bs))
                with torch.no_grad():
                    for _ in range(n_val_batches):
                        x, y = get_batch(val_tokens, val_bs, seq_len,
                                         device, val_rng)
                        with torch.autocast(device_type=device_type,
                                            dtype=amp_dtype, enabled=use_amp):
                            vl = raw_model(x, y)
                        val_losses.append(vl.item())
                val_loss = sum(val_losses) / len(val_losses)
                print(f"  >> val_loss: {val_loss:.4f}"
                      f" (best: {best_val_loss:.4f})")

                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    ckpt_path = os.path.join(args.output_dir, "nca_best.pt")
                    torch.save({
                        "model_state_dict": raw_model.state_dict(),
                        "config": model_config,
                        "step": step,
                        "val_loss": val_loss,
                    }, ckpt_path)
                    print(f"  >> saved best checkpoint: {ckpt_path}")

            step += 1

    # Save final checkpoint (rank 0 only)
    if is_main:
        final_path = os.path.join(args.output_dir, "nca_final.pt")
        torch.save({
            "model_state_dict": raw_model.state_dict(),
            "config": model_config,
            "step": total_steps,
            "val_loss": best_val_loss,
        }, final_path)

        elapsed = time.time() - t0
        print(f"\nTraining complete in {elapsed:.1f}s")
        print(f"Best val loss: {best_val_loss:.4f}")
        print(f"Saved: {final_path}")

    cleanup_distributed()
    return best_val_loss


def main():
    parser = argparse.ArgumentParser(description="NCA pre-pre-training")
    parser.add_argument("--data-dir", type=str, required=True)
    parser.add_argument("--output-dir", type=str, default="./nca_checkpoints")
    parser.add_argument("--config", type=str, default="tiny",
                        choices=list(CONFIGS.keys()))
    parser.add_argument("--device", type=str, default=None)
    parser.add_argument("--seq-len", type=int, default=1024)
    parser.add_argument("--epochs", type=int, default=None,
                        help="Override config epochs")
    parser.add_argument("--lr", type=float, default=None,
                        help="Override config learning rate")
    parser.add_argument("--batch-size", type=int, default=None,
                        help="Override config batch size")
    parser.add_argument("--grad-accum", type=int, default=None,
                        help="Override config gradient accumulation steps")
    parser.add_argument("--no-compile", action="store_true",
                        help="Disable torch.compile")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # Apply overrides
    if args.epochs is not None:
        CONFIGS[args.config]["epochs"] = args.epochs
    if args.lr is not None:
        CONFIGS[args.config]["lr"] = args.lr
    if args.batch_size is not None:
        CONFIGS[args.config]["batch_size"] = args.batch_size
    if args.grad_accum is not None:
        CONFIGS[args.config]["grad_accum"] = args.grad_accum

    train(args)


if __name__ == "__main__":
    main()
